spring.application.name=nilapp
server.port=8082
server.address=0.0.0.0


spring.datasource.url=jdbc:postgresql://atm-heroes-database.cef6kw2im6ds.us-east-1.rds.amazonaws.com:5432/nilapp_database
spring.datasource.username=postgres
spring.datasource.password=mld-atm-heroes-database
#spring.datasource.username=wc_app_user
#spring.datasource.password=yourStrongPassword

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#spring.datasource.url= jdbc:postgresql://localhost:5432/worldcupbracket
#spring.datasource.username= postgres
#spring.datasource.password= postgres
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# hibernate follow my naming conventions
# TODO does this work
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= validate

# Logging
logging.level.org.hibernate.SQL= DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# TODO not sure if this is correct get rid of error
spring.jpa.properties.hibernate.validator.apply_to_ddl=false



#spring.web.cors.allowed-origins=http://localhost:4200
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.web.cors.allowed-headers=*
#spring.web.cors.allow-credentials=true

# Max request size (JSON body)
#spring.servlet.multipart.max-request-size=1MB
#spring.servlet.multipart.max-file-size=1MB
#
## Max HTTP post size
#server.max-http-request-size=102400
## Server timeout
#spring.mvc.async.request-timeout=10s
#
## Async timeout
#spring.mvc.async.request-timeout=10s
#
## Tomcat thread timeout
#server.tomcat.connection-timeout=10000
#spring.datasource.hikari.connection-timeout=10000
#spring.datasource.hikari.validation-timeout=5000
#spring.datasource.hikari.idle-timeout=60000
#spring.datasource.hikari.max-lifetime=1800000
#spring.webclient.connect-timeout=5000
#spring.webclient.read-timeout=5000


# show 404 urls
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false



