DROP Table IF EXISTS achievement_types CASCADE;
DROP Table IF EXISTS achievements CASCADE;
DROP Table IF EXISTS affiliations CASCADE;
DROP Table IF EXISTS contribution_statuses CASCADE;
DROP Table IF EXISTS contributions CASCADE;
DROP Table IF EXISTS daily_stats CASCADE;
DROP Table IF EXISTS entities CASCADE;
DROP Table IF EXISTS entity_affiliations CASCADE;
DROP Table IF EXISTS entity_types CASCADE;
DROP Table IF EXISTS friend_statuses CASCADE;
DROP Table IF EXISTS friends CASCADE;
DROP Table IF EXISTS goals CASCADE;
DROP Table IF EXISTS group_achievements CASCADE;
DROP Table IF EXISTS group_goal_histories CASCADE;
DROP Table IF EXISTS group_goals CASCADE;
DROP Table IF EXISTS groups CASCADE;
DROP Table IF EXISTS payout_batches CASCADE;
DROP Table IF EXISTS sponsor_campaigns CASCADE;
DROP Table IF EXISTS sponsors CASCADE;
DROP Table IF EXISTS user_achievements CASCADE;
DROP Table IF EXISTS user_entities CASCADE;
DROP Table IF EXISTS user_goal_histories CASCADE;
DROP Table IF EXISTS user_goals CASCADE;
DROP Table IF EXISTS user_groups CASCADE;
DROP Table IF EXISTS users CASCADE ;


CREATE TABLE "users" (
                         "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar(50) UNIQUE NOT NULL,
                         "first_name" varchar(50) NOT NULL,
                         "last_name" varchar(50) NOT NULL,
                         "middle_name" varchar(50),
                         "email" varchar(100) UNIQUE NOT NULL,
                         "phone" varchar(20) UNIQUE NOT NULL,
                         "password" text NOT NULL,
                         "total_lifetime_coins" bigint,
                         "birthday" date,
                         "birth_year" varchar,
                         "created_at" timestamp DEFAULT (now()),
                         "updated_at" timestamp DEFAULT (now()),
                         "state" varchar(50),
                         "country" varchar(50),
                         "city" varchar(50),
                         "county" varchar(50),
                         "language" varchar DEFAULT 'english',
                         "timezone" varchar DEFAULT 'America/New_York',
                         "force_password_change" bool DEFAULT false,
                         "session_id" varchar
);

CREATE TABLE "entities" (
                            "entity_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar(100) NOT NULL,
                            "abbreviation" varchar(10),
                            "associated_school" varchar(100),
                            "type" bigint,
                            "is_active" bool,
                            "primary_color" varchar,
                            "secondary_color" varchar,
                            "sporting_affiliations" bigint,
                            "tax_id" varchar(20)
);

CREATE TABLE "user_entities" (
                                 "user_entities_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "entity_id" bigint,
                                 "user_id" bigint
);

CREATE TABLE "entity_types" (
                                "entity_types_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "type" varchar(100) NOT NULL,
                                "description" varchar(100)
);

CREATE TABLE "daily_stats" (
                               "daily_stat_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "user_id" bigint NOT NULL,
                               "date" date NOT NULL,
                               "total_steps" int DEFAULT 0,
                               "coins" int DEFAULT 0,
                               "distance_meters" int,
                               "device_source" varchar,
                               "sync_timestamp" timestamp,
                               "calories" int DEFAULT 0,
                               "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "contributions" (
                                 "contribution_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "user_id" bigint NOT NULL,
                                 "entity_id" bigint NOT NULL,
                                 "campaign_id" bigint NOT NULL,
                                 "steps_contributed" int DEFAULT 0,
                                 "coins_contributed" int DEFAULT 0,
                                 "conversion_rate" decimal(10,6),
                                 "ad_session_id" varchar(100),
                                 "created_at" timestamp DEFAULT (now()),
                                 "payout_batch_id" bigint,
                                 "status" bigint NOT NULL DEFAULT 1
);

CREATE TABLE "payout_batches" (
                                  "payout_batch_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "entity_id" int,
                                  "amount_paid" decimal(15,2),
                                  "transaction_ref" varchar(100),
                                  "period_start" date,
                                  "period_end" date,
                                  "s3_manifest_url" text
);

CREATE TABLE "affiliations" (
                                "affiliation_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "name" varchar NOT NULL
);

CREATE TABLE "entity_affiliations" (
                                       "entity_affiliation_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "entity_id" bigint,
                                       "affiliation_id" bigint
);

CREATE TABLE "goals" (
                         "goal_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "entity_id" bigint NOT NULL,
                         "achievement_id" bigint,
                         "goal" varchar(255),
                         "description" varchar(255),
                         "completed_date" timestamp,
                         "goal_lock_date" timestamp
);

-- CREATE TABLE "user_goals" (
--                               "user_goal_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                               "user_id" bigint NOT NULL,
--                               "goal_id" bigint NOT NULL,
--                               "allocation_pct" decimal(5,2) NOT NULL DEFAULT 0,
--                               "joined_at" timestamp DEFAULT (now()),
--                               "left_at" timestamp,
--                               "is_active" bool DEFAULT true,
--                               "is_completed" bool DEFAULT false
-- );
--
-- CREATE TABLE "user_goal_histories" (
--                                        "user_goal_history_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                        "user_id" bigint NOT NULL,
--                                        "goal_id" bigint NOT NULL,
--                                        "allocation_pct" decimal(5,2),
--                                        "joined_at" timestamp NOT NULL,
--                                        "left_at" timestamp,
--                                        "coins_contributed" int DEFAULT 0,
--                                        "steps_contributed" int DEFAULT 0
-- );

CREATE TABLE "achievements" (
                                "achievement_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "achievement_type" int NOT NULL,
                                "achievement" varchar(255),
                                "description" varchar(255),
                                "badge" varchar(255),
                                "required_steps" bigint,
                                "required_distance" bigint,
                                "required_coins" bigint
);

CREATE TABLE "achievement_types" (
                                     "achievement_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "type" varchar(50),
                                     "meaning" varchar(100)
);

CREATE TABLE "user_achievements" (
                                     "user_achievements_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "user_id" bigint,
                                     "achievement_id" bigint,
                                     "earned_at" date
);

CREATE TABLE "sponsors" (
                            "sponsor_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar(100),
                            "type" varchar(50),
                            "contact_email" varchar,
                            "is_active" bool
);

CREATE TABLE "sponsor_campaigns" (
                                     "campaign_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "sponsor_id" bigint,
                                     "entity_id" bigint,
                                     "payout_per_step" decimal(10,6),
                                     "payout_per_coin" decimal(10,6),
                                     "start_date" date,
                                     "end_date" date
);

CREATE TABLE "contribution_statuses" (
                                         "contribution_status_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "code" varchar(50) UNIQUE NOT NULL,
                                         "label" varchar(100),
                                         "description" text
);

CREATE TABLE "friends" (
                           "friends_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "user_id" bigint NOT NULL,
                           "friend_id" bigint NOT NULL,
                           "status" int DEFAULT 1,
                           "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "friend_statuses" (
                                   "friend_status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "status" varchar(100) DEFAULT 'pending',
                                   "description" varchar(100)
);

CREATE TABLE "groups" (
                          "group_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar(100),
                          "entities" varchar
);

CREATE TABLE "group_achievements" (
                                      "group_achievements_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "group_id" bigint,
                                      "achievement_id" bigint,
                                      "earned_at" date
);

-- CREATE TABLE "group_goals" (
--                                "group_goal_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                "group_id" bigint NOT NULL,
--                                "goal_id" bigint NOT NULL,
--                                "allocation_pct" decimal(5,2) NOT NULL DEFAULT 0,
--                                "joined_at" timestamp DEFAULT (now()),
--                                "left_at" timestamp,
--                                "is_active" bool DEFAULT true
-- );
--
-- CREATE TABLE "group_goal_histories" (
--                                         "group_goal_history_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                         "group_id" bigint NOT NULL,
--                                         "group_goal_id" bigint NOT NULL,
--                                         "allocation_pct" decimal(5,2),
--                                         "joined_at" timestamp NOT NULL,
--                                         "left_at" timestamp,
--                                         "coins_contributed" int DEFAULT 0,
--                                         "steps_contributed" int DEFAULT 0
-- );

CREATE TABLE "user_groups" (
                               "user_groups_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "group_id" bigint,
                               "user_id" bigint
);

CREATE INDEX ON "user_entities" ("entity_id", "user_id");

CREATE UNIQUE INDEX ON "daily_stats" ("user_id", "date");

CREATE INDEX ON "contributions" ("entity_id", "created_at");

CREATE INDEX ON "entity_affiliations" ("entity_id", "affiliation_id");

CREATE UNIQUE INDEX ON "user_goals" ("user_id", "goal_id");

CREATE INDEX ON "user_achievements" ("user_id", "achievement_id");

CREATE UNIQUE INDEX ON "friends" ("user_id", "friend_id");

CREATE UNIQUE INDEX ON "group_achievements" ("group_id", "achievement_id");

CREATE UNIQUE INDEX ON "group_goals" ("group_id", "goal_id");

CREATE INDEX ON "user_groups" ("group_id", "user_id");

COMMENT ON COLUMN "entity_types"."type" IS 'ex COLLECTIVE, SCHOOL_DIRECT, SCHOLARSHIP_FUND';

COMMENT ON COLUMN "entity_types"."description" IS 'ex paid to school, paid to collective';

COMMENT ON COLUMN "achievement_types"."type" IS 'GOAL';

COMMENT ON COLUMN "friend_statuses"."status" IS 'accepted  -- pending, accepted, blocked';

COMMENT ON COLUMN "groups"."entities" IS 'if we attach entities to groups';

ALTER TABLE "contributions" ADD FOREIGN KEY ("campaign_id") REFERENCES "sponsor_campaigns" ("campaign_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("payout_batch_id") REFERENCES "payout_batches" ("payout_batch_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("status") REFERENCES "contribution_statuses" ("contribution_status_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goals" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("achievement_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "friends" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "daily_stats" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payout_batches" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sponsor_campaigns" ADD FOREIGN KEY ("sponsor_id") REFERENCES "sponsors" ("sponsor_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entity_affiliations" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entity_affiliations" ADD FOREIGN KEY ("affiliation_id") REFERENCES "affiliations" ("affiliation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goals" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_achievements" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("achievement_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_achievements" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "achievements" ADD FOREIGN KEY ("achievement_type") REFERENCES "achievement_types" ("achievement_type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_goals" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_goals" ADD FOREIGN KEY ("goal_id") REFERENCES "goals" ("goal_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_goal_histories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_goal_histories" ADD FOREIGN KEY ("goal_id") REFERENCES "goals" ("goal_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entities" ADD FOREIGN KEY ("type") REFERENCES "entity_types" ("entity_types_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "friends" ADD FOREIGN KEY ("status") REFERENCES "friend_statuses" ("friend_status_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_entities" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_entities" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "group_achievements" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("group_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "group_achievements" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("achievement_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_groups" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("group_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_groups" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "group_goal_histories" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("group_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "group_goal_histories" ADD FOREIGN KEY ("group_goal_id") REFERENCES "group_goals" ("group_goal_id") DEFERRABLE INITIALLY IMMEDIATE;
