DROP Table IF EXISTS achievement_types CASCADE;
DROP Table IF EXISTS achievements CASCADE;
DROP Table IF EXISTS affiliations CASCADE;
DROP Table IF EXISTS contribution_statuses CASCADE;
DROP Table IF EXISTS contributions CASCADE;
DROP Table IF EXISTS daily_stats CASCADE;
DROP Table IF EXISTS entities CASCADE;
DROP Table IF EXISTS entity_achievements CASCADE;
DROP Table IF EXISTS entity_affiliations CASCADE;
DROP Table IF EXISTS entity_types CASCADE;
DROP Table IF EXISTS friend_statuses CASCADE;
DROP Table IF EXISTS friends CASCADE;
DROP Table IF EXISTS goal_instances CASCADE;
DROP Table IF EXISTS goals CASCADE;
DROP Table IF EXISTS goal_types CASCADE;
DROP Table IF EXISTS group_achievements CASCADE;
DROP Table IF EXISTS group_goal_histories CASCADE; -- deleted
DROP Table IF EXISTS group_goals CASCADE; -- deleted
DROP Table IF EXISTS groups CASCADE;
DROP Table IF EXISTS payout_batches CASCADE;
DROP Table IF EXISTS sponsor_campaigns CASCADE;
DROP Table IF EXISTS sponsors CASCADE;
DROP Table IF EXISTS user_achievements CASCADE;
DROP Table IF EXISTS user_entities CASCADE;
DROP Table IF EXISTS user_goal_histories CASCADE; -- deleted
DROP Table IF EXISTS user_goals CASCADE;
DROP Table IF EXISTS user_groups CASCADE;
DROP Table IF EXISTS user_progress CASCADE;
DROP Table IF EXISTS users CASCADE ;
-- TODO make sure all tables are in drop list

CREATE TABLE "users" (
                         "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar(50) UNIQUE NOT NULL,
                         "first_name" varchar(50) NOT NULL,
                         "last_name" varchar(50) NOT NULL,
                         "middle_name" varchar(50),
                         "email" varchar(100) UNIQUE NOT NULL,
                         "phone" varchar(20) UNIQUE NOT NULL,
                         "password" text NOT NULL,
                         "total_lifetime_coins" bigint,
                         "birthday" date,
                         "birth_year" varchar,
                         "created_at" timestamp DEFAULT (now()),
                         "updated_at" timestamp DEFAULT (now()),
                         "state" varchar(50),
                         "country" varchar(50),
                         "city" varchar(50),
                         "county" varchar(50),
                         "language" varchar DEFAULT 'english',
                         "timezone" varchar DEFAULT 'America/New_York',
                         "force_password_change" bool DEFAULT false,
                         "session_id" varchar
);

CREATE TABLE "entities" (
                            "entity_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar(100) NOT NULL,
                            "abbreviation" varchar(10),
                            "associated_school" varchar(100),
                            "type" bigint,
                            "is_active" bool,
                            "primary_color" varchar,
                            "secondary_color" varchar,
                            "sporting_affiliations" bigint,
                            "tax_id" varchar(20)
);

CREATE TABLE "user_entities" (
                                 "user_entities_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "entity_id" bigint,
                                 "user_id" bigint
);

CREATE TABLE "entity_types" (
                                "entity_types_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "type" varchar(100) NOT NULL,
                                "description" varchar(100)
);

CREATE TABLE "daily_stats" (
                               "daily_stat_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "user_id" bigint NOT NULL,
                               "date" date NOT NULL,
                               "total_steps" int DEFAULT 0,
                               "coins" int DEFAULT 0,
                               "distance_meters" int,
                               "device_source" varchar,
                               "sync_timestamp" timestamp,
                               "calories" int DEFAULT 0,
                               "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "contributions" (
                                 "contribution_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "user_id" bigint NOT NULL,
                                 "entity_id" bigint NOT NULL,
                                 "campaign_id" bigint NOT NULL,
                                 "steps_contributed" int DEFAULT 0,
                                 "coins_contributed" int DEFAULT 0,
                                 "conversion_rate" decimal(10,6),
                                 "ad_session_id" varchar(100),
                                 "created_at" timestamp DEFAULT (now()),
                                 "payout_batch_id" bigint,
                                 "contribution_status_id" int NOT NULL DEFAULT 1,
--                                  "contribution_type_id" INT NOT NULL REFERENCES contribution_types(contribution_type_id),  // added later TODO just use this
--                                  allocation_snapshot JSONB;  // added later TODO just use this
);

CREATE TABLE "payout_batches" (
                                  "payout_batch_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "entity_id" int,
                                  "amount_paid" decimal(15,2),
                                  "transaction_ref" varchar(100),
                                  "period_start" date,
                                  "period_end" date,
                                  "s3_manifest_url" text
);

CREATE TABLE "affiliations" (
                                "affiliation_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "name" varchar NOT NULL
);

CREATE TABLE "entity_affiliations" (
                                       "entity_affiliations_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "entity_id" bigint,
                                       "affiliation_id" bigint
);

CREATE TABLE "achievements" (
                                "achievement_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "achievement_type" int NOT NULL,
                                "achievement" varchar(255),
                                "description" varchar(255),
                                "badge" varchar(255),
                                "required_steps" bigint,
                                "required_distance" bigint,
                                "required_coins" bigint
);

CREATE TABLE "achievement_types" (
                                     "achievement_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "type" varchar(50),
                                     "meaning" varchar(100)
);

CREATE TABLE "sponsors" (
                            "sponsor_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar(100),
                            "type" varchar(50),
                            "contact_email" varchar,
                            "is_active" bool
);

CREATE TABLE "sponsor_campaigns" (
                                     "campaign_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "sponsor_id" bigint,
                                     "entity_id" bigint,
                                     "payout_per_step" decimal(10,6),
                                     "payout_per_coin" decimal(10,6),
                                     "start_date" date,
                                     "end_date" date
);

CREATE TABLE "contribution_statuses" (
                                         "contribution_status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "code" varchar(50) UNIQUE NOT NULL,
                                         "label" varchar(100),
                                         "description" text
);

CREATE TABLE "friends" (
                           "friends_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "user_id" bigint NOT NULL,
                           "friend_id" bigint NOT NULL,
                           "status" int DEFAULT 1,
                           "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "friend_statuses" (
                                   "friend_status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "status" varchar(50) DEFAULT 'pending',
                                   "description" varchar(100)
);

CREATE TABLE "groups" (
                          "group_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar(100),
                          "entities" varchar
);

CREATE TABLE "group_achievements" (
                                      "group_achievements_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "group_id" bigint,
                                      "achievement_id" bigint,
                                      "earned_at" date
);

CREATE TABLE "user_achievements" (
                                     "user_achievements_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "user_id" bigint,
                                     "achievement_id" bigint,
                                     "earned_at" date
);

CREATE TABLE "entity_achievements" (
                                       "entity_achievement_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "entity_id" bigint,
                                       "achievement_id" bigint,
                                       "earned_at" date
);

CREATE TABLE "goals" (
                         "goal_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "goal_types_id" int NOT NULL,
                         "achievement_id" bigint,
                         "goal" varchar(255),
                         "description" varchar(255),
                         "completed_date" timestamp,
                         "goal_lock_date" timestamp
);

CREATE TABLE "goal_types" (
                              "goal_types_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "type" varchar(255),
                              "description" varchar(255)
);

CREATE TABLE "goal_instances" (
                                  "goal_instance_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "goal_id" bigint NOT NULL,
                                  "entity_id" bigint,
                                  "group_id" bigint,
                                  "start_date" date default now(),
                                  "end_date" date,
                                  "current_progress" decimal(10,6) DEFAULT 0.00,
                                  "is_active" bool DEFAULT true,
                                  "is_complete" bool DEFAULT false,
                                  "steps_contributed" int NOT NULL DEFAULT 0,
                                  "coins_contributed" int NOT NULL DEFAULT 0,
                                  "steps_needed" int,
                                  "coins_needed" int,
                                  "dollar_amount"  decimal(10,6) NOT NULL,
);

CREATE TABLE "user_goals" (
                              "user_goal_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "user_id" bigint NOT NULL,
                              "goal_instance_id" bigint NOT NULL,
                              "allocation_pct" decimal(5,2) NOT NULL DEFAULT 0,
                              "joined_at" timestamp DEFAULT (now()),
                              "left_at" timestamp,
                              "is_active" bool DEFAULT true,
                              "is_complete" bool DEFAULT false
);

CREATE TABLE "user_progress" (
                                 "user_progress_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "user_goal_id" bigint NOT NULL,
                                 "steps_contributed" int NOT NULL DEFAULT 0,
                                 "coins_contributed" int NOT NULL DEFAULT 0,
                                 "recorded_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_groups" (
                               "user_groups_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "group_id" bigint,
                               "user_id" bigint
);
CREATE TABLE group_entities (
                                group_entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                group_id BIGINT NOT NULL,
                                entity_id BIGINT NOT NULL,

                                CONSTRAINT fk_group
                                    FOREIGN KEY (group_id) REFERENCES groups(group_id)
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_entity
                                    FOREIGN KEY (entity_id) REFERENCES entities(entity_id)
                                        ON DELETE CASCADE,

                                CONSTRAINT uq_group_entity UNIQUE (group_id, entity_id)
);

CREATE TABLE contribution_types (
                                    contribution_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    code        TEXT UNIQUE NOT NULL,   -- e.g. 'AD', 'SURVEY', 'BONUS'
                                    label       TEXT NOT NULL,          -- human-readable name
                                    description TEXT
);
CREATE TABLE user_streaks (
                              user_streak_id BIGSERIAL PRIMARY KEY,
                              user_id BIGINT NOT NULL,
                              current_streak INT DEFAULT 0,
                              longest_streak INT DEFAULT 0,
                              last_completed_date DATE,
                              streak_shields INT DEFAULT 0,
                              streak_savers INT DEFAULT 0,
                              created_at TIMESTAMP DEFAULT NOW(),
                              updated_at TIMESTAMP DEFAULT NOW(),

                              CONSTRAINT fk_user_streak_user
                                  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- contribution_id	group_id	coins	allocation_percentage
-- 123	3	70	70
-- 123	9	30	30
-- // TODO make sure this works
ALTER TABLE contributions
    ADD COLUMN allocation_snapshot JSONB;
-- {
-- "entityAllocations": [
--     { "entityId": 1, "percentage": 25 },
--     { "entityId": 2, "percentage": 50 },
--     { "entityId": 3, "percentage": 25 }
--   ],
--   "groupAllocations": [
--     { "groupId": 1, "percentage": 100 }
--   ]
--   "adValue": 0.004,
--   "coinValue": 1,
--   "coinsEarned": 100,
--   "steps": 8000
-- }
-- // TODO make sure this works
ALTER TABLE contributions
    ADD COLUMN contribution_type_id INT NOT NULL DEFAULT 1;
-- // TODO make sure this works
ALTER TABLE contributions
    ADD CONSTRAINT fk_contribution_type
        FOREIGN KEY (contribution_type_id)
            REFERENCES contribution_types(contribution_type_id);
-- ALTER TABLE contributions
--     ADD CONSTRAINT chk_contribution_type_valid
--         CHECK (contribution_type_id IN (SELECT contribution_type_id FROM contribution_types));
--         OPTIONAL (BUT RECOMMENDED)
-- If you want to enforce valid types only:

-- // TODO make sure this works
ALTER TABLE user_entities
ADD COLUMN joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN left_at TIMESTAMP NULL;
ALTER TABLE user_groups
ADD COLUMN joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN left_at TIMESTAMP NULL;
ALTER TABLE user_goals
ADD COLUMN completed_at TIMESTAMP NULL;

ALTER TABLE user_achievements
ALTER COLUMN earned_at TYPE TIMESTAMP;
ALTER TABLE entity_achievements
ALTER COLUMN earned_at TYPE TIMESTAMP;
ALTER TABLE group_achievements
ALTER COLUMN earned_at TYPE TIMESTAMP;

ALTER TABLE groups DROP COLUMN entities;

CREATE INDEX ON "user_entities" ("entity_id", "user_id");

CREATE UNIQUE INDEX ON "daily_stats" ("user_id", "date");

CREATE INDEX ON "contributions" ("entity_id", "created_at");

CREATE INDEX ON "entity_affiliations" ("entity_id", "affiliation_id");

CREATE UNIQUE INDEX ON "friends" ("user_id", "friend_id");

CREATE UNIQUE INDEX ON "group_achievements" ("group_id", "achievement_id");

CREATE INDEX ON "user_achievements" ("user_id", "achievement_id");

CREATE INDEX ON "entity_achievements" ("entity_id", "achievement_id");

CREATE UNIQUE INDEX ON "user_goals" ("user_id", "goal_instance_id");

CREATE INDEX ON "user_groups" ("group_id", "user_id");

COMMENT ON COLUMN "entity_types"."type" IS 'ex COLLECTIVE, SCHOOL_DIRECT, SCHOLARSHIP_FUND';

COMMENT ON COLUMN "entity_types"."description" IS 'ex paid to school, paid to collective';

COMMENT ON COLUMN "achievement_types"."type" IS 'GOAL';

COMMENT ON COLUMN "friend_statuses"."status" IS 'accepted  -- pending, accepted, blocked';

COMMENT ON COLUMN "groups"."entities" IS 'if we attach entities to groups';

COMMENT ON COLUMN "goal_types"."type" IS '(APP, ENTITY, GROUP)';

ALTER TABLE "contributions" ADD FOREIGN KEY ("campaign_id") REFERENCES "sponsor_campaigns" ("campaign_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("payout_batch_id") REFERENCES "payout_batches" ("payout_batch_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("contribution_status_id") REFERENCES "contribution_statuses" ("contribution_status_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "friends" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goals" ADD FOREIGN KEY ("goal_types_id") REFERENCES "goal_types" ("goal_types_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goals" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("achievement_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goal_instances" ADD FOREIGN KEY ("goal_id") REFERENCES "goals" ("goal_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goal_instances" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goal_instances" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("group_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_goals" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_goals" ADD FOREIGN KEY ("goal_instance_id") REFERENCES "goal_instances" ("goal_instance_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_progress" ADD FOREIGN KEY ("user_goal_id") REFERENCES "user_goals" ("user_goal_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "achievements" ADD FOREIGN KEY ("achievement_type") REFERENCES "achievement_types" ("achievement_type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "group_achievements" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("achievement_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "daily_stats" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entity_affiliations" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entity_affiliations" ADD FOREIGN KEY ("affiliation_id") REFERENCES "affiliations" ("affiliations_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entity_achievements" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entity_achievements" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("achievement_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entities" ADD FOREIGN KEY ("type") REFERENCES "entity_types" ("entity_types_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_entities" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "friends" ADD FOREIGN KEY ("status") REFERENCES "friend_statuses" ("friend_status_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "group_achievements" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("group_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_groups" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("group_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sponsor_campaigns" ADD FOREIGN KEY ("sponsor_id") REFERENCES "sponsors" ("sponsor_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payout_batches" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("entity_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_achievements" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("achievement_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_achievements" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_entities" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_groups" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
